apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    app: nginx
  annotations:
    configmap.reloader.stakater.com/reload: "test-deploy-configmap"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80